### ISSUE TITLE
minor issue with file extension of disaggregate data file saved to box

### ISSUE THREAD

**Issue by alexmitrani** [BayAreaMetro/travel-model-one#46]
In the script file https://github.com/BayAreaMetro/travel-model-one/blob/master/utilities/bespoke-requests/fare-study/RunIteration4.bat, on line 354 it aims to save an .rds file to Box and it does, but with a .csv file extension.  Not a big issue but a little confusing.  

Thanks.

Alex

**Comment by lmz** [comment]
Sorry about that typo!  Was getting in that change too fast.
Fixed in https://github.com/BayAreaMetro/travel-model-one/commit/bd5d4ab5784431a3f76dce910316d36ab91729e2

**Comment by alexmitrani** [comment]
Thanks very much :-)
